name = "advent_of_code_2025"
description = "Ada solutions to Advent of Code 2025"
version = "0.1.0-dev"

authors = ["David Joseph Haley"]
maintainers = ["David Joseph Haley <david.haley@bigpond.com>"]
maintainers-logins = ["David-Haley"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = ""
tags = ["aoc2025"]

executables = ["advent_of_code_2025"]
